# =============================================================================
# Global Costmap Parameters
# =============================================================================
global_costmap:
  global_frame: map
  robot_base_frame: base_link
  transform_tolerance: 2.0
  update_frequency: 2.0
  publish_frequency: 0.5
  static_map: false
  rolling_window: true        # 在没有外部地图（/map）输入的情况下，rolling_window 不能设为 false。
  resolution: 0.05
  width: 20.0                  # 地图宽度（米）
  height: 20.0                 # 地图高度（米）
  origin_x: -10.0              # 让初始位置（map 原点）位于地图中心
  origin_y: -10.0

  plugins:
    # - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
